# 1. Write a python program to display all the header tags from ‘en.wikipedia.org/wiki/Main_Page’

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

wiki = requests.get('https://en.wikipedia.org/wiki/Main_Page')
soup = BeautifulSoup(wiki.text, 'html.parser')

head_tag=soup.find_all(['h1','h2','h3'])
Header =[]
for i in head_tag:
    Header.append(i.get_text().replace("\n",""))


Wikipedia_Header=pd.DataFrame({})
Wikipedia_Header['Wikipedia Main Page Header Tag']=Header
print('\033[1m'+'Wikipedia Main Page Header Tag'+'\033[0m')
Wikipedia_Header

Wikipedia Main Page Header Tag

  Wikipedia Main Page Header Tag
0                      Main Page
1           Welcome to Wikipedia
2  From today's featured article
3               Did you know ...
4                    In the news
5                    On this day
6       Today's featured picture
7       Other areas of Wikipedia
8    Wikipedia's sister projects
9            Wikipedia languages

3. Write a python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have toscrape:
i) Top 10 ODI teams in men’s cricket along with the records for matches, points andrating.

ii) Top 10 ODI Batsmen in men along with the records of their team and rating.

iii) Top 10 ODI bowlers along with the records of their team and rating

In [7]:
from bs4 import BeautifulSoup
import urllib.request
import pandas as pd
import requests

url = 'https://www.icc-cricket.com/rankings/mens/team-rankings/odi'

response = requests.get(url)
print(response.status_code, '--->',url)
print('\n')
soup= BeautifulSoup(response.content, 'lxml')


Team=[]
Matches=[]
Points=[]
Rating=[]
Country = soup.find_all('span',class_="u-hide-phablet")
for i in Country:
    Team.append(i.get_text().replace("\n",""))
    Team=Team[0:10]

match=soup.find_all('td',class_='rankings-block__banner--matches')
matchs=soup.find_all('td',class_='table-body__cell u-center-text')
mtc = match + matchs

for i in mtc:
    Matches.append(i.text)
    Matches=Matches[0:10]
    
pt=soup.find_all('td',class_="rankings-block__banner--points")
pts= soup.find_all('td',class_ ="table-body__cell u-center-text")
Point= pt + pts
for i in Point:
    Points.append(i.get_text().replace("\n",""))
    Points=Points[0:10]
rating = soup.find_all('td',class_="table-body__cell u-text-right rating")
for i in rating:
    Rating.append(i.get_text().replace("\n",""))
    Rating=Rating[0:10]
    
ODI=pd.DataFrame({})
ODI['Country']=Team
ODI['Matches']=Matches
ODI['Rating']=Rating
ODI['Points']=Points
print('\033[1m'+'ICC MENS ODI RANKING'+'\033[0m') # Print Title in bold case
ODI

200 ---> https://www.icc-cricket.com/rankings/mens/team-rankings/odi


ICC MENS ODI RANKING

        Country Matches Rating Points
0     Australia      23    116  2,714
1      Pakistan      20    115     20
2         India   2,316    104  2,316
3   New Zealand      33    101     33
4       England   3,807    101  3,807
5  South Africa      27     98     27
6    Bangladesh   2,806     88  2,806
7   Afghanistan      24     80     24
8     Sri Lanka   2,426     72  2,426
9   West Indies      19     51     19

ii) Top 10 ODI Batsmen in men along with the records of their team and rating.

iii) Top 10 ODI bowlers along with the records of their team and rating

In [9]:
# ICC ODI Mens Bowling Ranking

import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

url = 'https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36'
}

response = requests.get(url)
print(response.status_code, '--->',url)
print('\n\n')
soup= BeautifulSoup(response.content, 'lxml')
Position =[]
Player =[]
Country =[]
Rating =[]

# Extracting Data of Top Player from Banner
block_1= soup.find('tr', attrs={'class':'rankings-block__banner'}) # contains Top Player ranking detail

Position.append(block_1.find('td',class_='rankings-block__position').text)# Ranking Position
Player.append(block_1.find('div', class_="rankings-block__banner--name-large").text) # Extract Player Name
Country.append(block_1.find('span', class_='rankings-block__banner--nation').text)# Extract Country Name
Rating.append(block_1.find('div', class_="rankings-block__banner--rating").text) # Extract Rating

# Extracting other Player Ranking
table_rows =soup.find_all('tr', attrs={'class':'table-body'})

for row in table_rows[:10]:
    Position.append(row.find('td', class_='table-body__cell table-body__cell--position u-text-right').text.replace('\n',''))
    Player.append(row.find('a').text)
    Country.append(row.find('span', class_='table-body__logo-text').text)
    Rating.append(row.find('td', class_='table-body__cell rating').text)
    
# Storing data in Dataframe
ODI_Bowling=pd.DataFrame({'Ranking':Position,'Player_Name':Player, 'Team':Country, 'Rating':Rating})
print('\033[1m'+'ICC ODI MENS BOWLING RANKING'+'\033[0m') # Print Title in bold case
ODI_Bowling

200 ---> https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling



ICC ODI MENS BOWLING RANKING

,Ranking,Player_Name,Team,Rating
0,\n\n\n 1\n ...,Josh Hazlewood,,705
1,2 ...,Mohammed Siraj,IND,691
2,3 ...,Mitchell Starc,AUS,686
3,4 ...,Matt Henry,NZ,667
4,5 ...,Trent Boult,NZ,660
5,6 ...,Rashid Khan,AFG,659
6,7 ...,Adam Zampa,AUS,652
7,8 ...,Mujeeb Ur Rahman,AFG,637
8,9 ...,Mohammad Nabi,AFG,631
9,10 ...,Shaheen Afridi,PAK,630
10,11 ...,Alzarri Joseph,WI,625

6. Write a python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have toscrape:
i) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.

ii) Top 10 women’s ODI players along with the records of their team and rating.

iii) Top 10 women’s ODI all-rounder along with the records of their team and rating.

i) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.

In [10]:
from bs4 import BeautifulSoup
import urllib.request
import pandas as pd
import requests

url = 'https://www.icc-cricket.com/rankings/womens/team-rankings/odi'

response = requests.get(url)
print(response.status_code, '--->',url)
print('\n')
SOUP= BeautifulSoup(response.content, 'lxml')

# Creating empty list
Team=[]
Matches=[]
Points=[]
Rating=[]

# Extracting Team Name
Country = SOUP.find_all('span',class_="u-hide-phablet")
for i in Country:
    Team.append(i.get_text().replace("\n",""))
    Team=Team[0:10]
    
# Extracting No of Matches    
match=SOUP.find_all('td',class_='rankings-block__banner--matches')
matchs=SOUP.find_all('td',class_='table-body__cell u-center-text')
mtc = match + matchs
for i in  mtc:
    Matches.append(i.text)
    Matches=Matches[0:10]
    
# Extracting Points gain    
pt=SOUP.find_all('td',class_="rankings-block__banner--points")
pts= SOUP.find_all('td',class_ ="table-body__cell u-center-text")
Point= pt + pts
for i in Point:
    Points.append(i.get_text().replace("\n",""))
    Points=Points[0:10]
    # Extracting Rating
rat=SOUP.find_all('td',class_="rankings-block__banner--rating")

rating = SOUP.find_all('td',class_="table-body__cell u-text-right rating")
RATING=rat + rating
for i in RATING:
    Rating.append(i.get_text().replace("\n",""))
    Rating=Rating[0:10]
Rating

# Creating dataframe to store data
ODI=pd.DataFrame({})
ODI['Country']=Team
ODI['Matches']=Matches
ODI['Rating']=Rating
ODI['Points']=Points

print('\033[1m'+'ICC ODI WOMENS RANKING'+'\033[0m') # Print Title in bold case
ODI

200 ---> https://www.icc-cricket.com/rankings/womens/team-rankings/odi


ICC ODI WOMENS RANKING

,Country,Matches,Rating,Points
0,Australia,21,172 ...,"3,603"
1,England,28,119,28
2,South Africa,"3,342",119,"3,342"
3,India,26,104,26
4,New Zealand,"3,098",102,"3,098"
5,West Indies,27,94,27
6,Thailand,"2,820",75,"2,820"
7,Bangladesh,25,70,25
8,Pakistan,"2,553",62,"2,553"
9,Sri Lanka,27,53,27

ii) Top 10 women’s ODI players along with the records of their team and rating.

In [11]:
# ICC WOMENS Bating Ranking

import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

url = 'https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36'
}

response = requests.get(url)
print(response.status_code, '--->',url)
print('\n\n')
soup= BeautifulSoup(response.text, 'lxml')
Position =[]
Player =[]
Country =[]
Rating =[]

# Extracting Data of Top Player from Banner
block_1= soup.find('tr', attrs={'class':'rankings-block__banner'}) # contains Top Player ranking detail

Position.append(block_1.find('td',class_='rankings-block__position').text)# Ranking Position
Player.append(block_1.find('div', class_="rankings-block__banner--name-large").text) # Extract Player Name
Country.append(block_1.find('span', class_='rankings-block__banner--nation').text)# Extract Country Name
Rating.append(block_1.find('div', class_="rankings-block__banner--rating").text) # Extract Rating

# Extracting other Player Ranking
table_rows =soup.find_all('tr', attrs={'class':'table-body'})

for row in table_rows[:10]:
    Position.append(row.find('td', class_='table-body__cell table-body__cell--position u-text-right').text.replace('\n',''))
    Player.append(row.find('a').text)
    Country.append(row.find('span', class_='table-body__logo-text').text)
    Rating.append(row.find('td', class_='table-body__cell rating').text)
    
# Storing data in Dataframe
ODI_Batmans=pd.DataFrame({'Ranking':Position,'Player_Name':Player, 'Team':Country, 'Rating':Rating})

print('\033[1m'+'ICC ODI WOMENS BATTING RANKING'+'\033[0m') # Print Title in bold case
ODI_Batmans

200 ---> https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting



ICC ODI WOMENS BATTING RANKING

,Ranking,Player_Name,Team,Rating
0,\n\n\n 1\n ...,Beth Mooney,,754
1,2 ...,Laura Wolvaardt,SA,732
2,3 ...,Natalie Sciver,ENG,731
3,4 ...,Meg Lanning,AUS,717
4,5 ...,Harmanpreet Kaur,IND,716
5,6 ...,Smriti Mandhana,IND,714
6,7 ...,Chamari Athapaththu,SL,673
7,8 ...,Ellyse Perry,AUS,626
8,9 ...,Tammy Beaumont,ENG,595
9,10 ...,Stafanie Taylor,WI,588
10,= ...,Suzie Bates,NZ,588

iii) Top 10 women’s ODI all-rounder along with the records of their team and rating.

In [12]:
# ICC ODI Womens Bowling Ranking

import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

url = 'https://www.icc-cricket.com/rankings/womens/player-rankings/odi/bowling'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36'
}

response = requests.get(url)
print(response.status_code, '--->',url)
print('\n\n')
soup= BeautifulSoup(response.text, 'html.parser')
Position =[]
Player =[]
Country =[]
Rating =[]

# Extracting Data of Top Player from Banner
block_1= soup.find('tr', attrs={'class':'rankings-block__banner'}) # contains Top Player ranking detail

Position.append(block_1.find('td',class_='rankings-block__position').text)# Ranking Position
Player.append(block_1.find('div', class_="rankings-block__banner--name-large").text) # Extract Player Name
Country.append(block_1.find('span', class_='rankings-block__banner--nation').text)# Extract Country Name
Rating.append(block_1.find('div', class_="rankings-block__banner--rating").text) # Extract Rating

# Extracting other Player Ranking
table_rows =soup.find_all('tr', attrs={'class':'table-body'})

for row in table_rows[:10]:
    Position.append(row.find('td', class_='table-body__cell table-body__cell--position u-text-right').text.replace('\n',''))
    Player.append(row.find('a').text)
    Country.append(row.find('span', class_='table-body__logo-text').text)
    Rating.append(row.find('td', class_='table-body__cell rating').text)
    
# Storing data in Dataframe
ODI_Bowling=pd.DataFrame({'Ranking':Position,'Player_Name':Player, 'Team':Country, 'Rating':Rating})

print('\033[1m'+'ICC ODI WOMENS BOWLING RANKING'+'\033[0m') # Print Title in bold case
ODI_Bowling

200 ---> https://www.icc-cricket.com/rankings/womens/player-rankings/odi/bowling



ICC ODI WOMENS BOWLING RANKING

,Ranking,Player_Name,Team,Rating
0,\n\n\n 1\n ...,Sophie Ecclestone,,751
1,2 ...,Jess Jonassen,AUS,723
2,3 ...,Shabnim Ismail,SA,722
3,4 ...,Megan Schutt,AUS,704
4,5 ...,Hayley Matthews,WI,660
5,6 ...,Kate Cross,ENG,655
6,7 ...,Ayabonga Khaka,SA,634
7,8 ...,Rajeshwari Gayakwad,IND,617
8,9 ...,Marizanne Kapp,SA,598
9,10 ...,Deepti Sharma,IND,589
10,11 ...,Ellyse Perry,AUS,585

Write s python program to display list of respected former presidents of India(i.e. Name , Term ofoffice)
from https://presidentofindia.nic.in/former-presidents.htm and make data frame.

In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

page3=requests.get("https://presidentofindia.nic.in/former-presidents.htm")
page3

In [11]:
soup3=BeautifulSoup(page3.content,'html.parser')
soup3
President_Name=[]
Office_Term=[]
for i in soup3.find_all('h3'):
    President_Name.append(i.get_text(strip=True).split('(')[0])
for i in soup3.find_all('p'):
    Office_Term.append(i.get_text(strip=True))
President_Name
Office_Term

['Term of Office:25 July, 2017 to 25 July, 2022',
 'https://ramnathkovind.nic.in',
 'Term of Office:25 July, 2012 to 25 July, 2017',
 'http://pranabmukherjee.nic.in',
 'Term of Office:25 July, 2007 to 25 July, 2012',
 'http://pratibhapatil.nic.in',
 'Term of Office:25 July, 2002 to 25 July, 2007',
 'http://abdulkalam.nic.in',
 'Term of Office:25 July, 1997 to 25 July, 2002',
 'Term of Office:25 July, 1992 to 25 July, 1997',
 'Term of Office:25 July, 1987 to 25 July, 1992',
 'Term of Office:25 July, 1982 to 25 July, 1987',
 'Term of Office:25 July, 1977 to 25 July, 1982',
 'Term of Office:24 August, 1974 to 11 February, 1977',
 'Term of Office:3 May, 1969 to 20 July, 1969 and 24 August, 1969 to 24 August, 1974',
 'Term of Office:13 May, 1967 to 3 May, 1969',
 'Term of Office:13 May, 1962 to 13 May, 1967',
 'Term of Office:26 January, 1950 to 13 May, 1962',
 'Copyright © 2022 The Rashtrapati Bhavan.',
 'Page last updated on:22-July-2022 15:58 PM',
 "Website hosted by National Informatics Centre. Website Content provided by the President's Secretariat."]

5) Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world and
make data frame

In [12]:
#importing the required libraries
import requests
from bs4 import BeautifulSoup

page=requests.get("https://www.cnbc.com/world/?region=world")
page

soup=BeautifulSoup(page.text,'html.parser')
soup


Head_line=[]
for i in soup.find_all('div',class_='RiverHeadline-headline RiverHeadline-hasThumbnail'):
   Head_line.append(i.text)
Head_line
time=[]
for i in soup.find_all('time'):
   time.append(i.text)
time
page1 = requests.get("https://www.cnbc.com/world/?region=world") 
soup1 = BeautifulSoup(page1.content, "html.parser")


tags=soup1('a')

for tag in tags:
    # Get the data from href key
    print(tag.get('href', None), end = "\n")

#MainContent
//www.cnbc.com/
/live-tv/
/
/markets/
/pre-markets/
/us-markets/
/currencies/
/cryptocurrency/
/futures-and-commodities/
/bonds/
/funds-and-etfs/
/business/
/economy/
/finance/
/health-and-science/
/media/
/real-estate/
/energy/
/climate/
/transportation/
/industrials/
/retail/
/wealth/
/life/
/small-business/
/investing/
/personal-finance/
/fintech/
/financial-advisors/
/options-action/
/etf-street/
https://buffett.cnbc.com
/earnings/
/trader-talk/
/technology/
/cybersecurity/
/enterprise/
/internet/
/media/
/mobile/
/social-media/
/cnbc-disruptors/
/tech-guide/
/politics/
/white-house/
/policy/
/defense/
/congress/
/equity-opportunity/
/tv/
/live-tv
/live-audio/
/business-day/
/primetime-shows/
/live-tv/full-episodes/
/latest-video/
/top-video/
/video-ceo-interviews/
/documentaries/
/podcast/
/features/
/digital-original/
/live-tv/schedule/
/watchlist/
/investingclub/
/investingclub/charitable-trust/
/investingclub/analysis/
/investingclub/trade-alerts/
/investingclub/video/
/investingclub/homestretch/
/investingclub/jim-cramer-columns/
/investingclub/education/
/pro/
/pro/news/
/pro/
/2023/05/11/market-strategist-survey-forecast.html
#
#
/make-it/
https://www.cnbc.com/select/
//www.cnbc.com/select/credit-cards/
//www.cnbc.com/select/loans/
//www.cnbc.com/select/banking/
//www.cnbc.com/select/mortgages/
//www.cnbc.com/select/insurance/
//www.cnbc.com/select/credit-monitoring/
//www.cnbc.com/select/personal-finance/
//www.cnbc.com/select/small-business/
//www.cnbc.com/select/taxes/
//www.cnbc.com/select/low-credit-scores/
//www.cnbc.com/select/investing/
#
//www.cnbc.com/select/credit-cards/
//www.cnbc.com/select/credit-card-marketplace/
//www.cnbc.com/select/best-credit-cards/
//www.cnbc.com/select/best-rewards-credit-cards/
//www.cnbc.com/select/best-travel-credit-cards/
//www.cnbc.com/select/best-zero-interest-credit-cards/
//www.cnbc.com/select/best-balance-transfer-credit-cards/
//www.cnbc.com/select/best-cash-back-credit-cards/
//www.cnbc.com/select/best-credit-card-sign-up-bonuses/
//www.cnbc.com/select/the-best-credit-cards-for-building-credit/
#
//www.cnbc.com/select/loans/
//www.cnbc.com/select/personal-loan-marketplace/
//www.cnbc.com/select/best-personal-loans/
//www.cnbc.com/select/best-debt-consolidation-loans/
//www.cnbc.com/select/best-loans-for-refinancing-credit-card-debt/
//www.cnbc.com/select/6-personal-loans-thatll-get-you-funded-in-as-little-as-1-business-day/
//www.cnbc.com/select/best-small-personal-loans/
//www.cnbc.com/select/personal-loan-lenders-borrow-50000/
//www.cnbc.com/select/personal-loan-online-applications/
//www.cnbc.com/select/best-student-loan-refinance-companies/
#
//www.cnbc.com/select/banking/
//www.cnbc.com/select/savings-marketplace/
//www.cnbc.com/select/best-high-yield-savings-accounts/
//www.cnbc.com/select/best-brick-and-mortar-savings-accounts/
//www.cnbc.com/select/best-brick-mortar-checking-accounts/
//www.cnbc.com/select/best-no-fee-checking-accounts/
//www.cnbc.com/select/checking-accounts-with-no-overdraft-fees/
//www.cnbc.com/select/best-checking-account-bonuses/
//www.cnbc.com/select/best-money-market-accounts/
//www.cnbc.com/select/best-certificates-of-deposits/
//www.cnbc.com/select/best-credit-unions/
#
//www.cnbc.com/select/mortgages/
//www.cnbc.com/select/best-mortgage-lenders/
//www.cnbc.com/select/mortgage-lenders-for-a-small-down-payment/
//www.cnbc.com/select/best-mortgage-lenders-va-loans-usda-loans/
//www.cnbc.com/select/best-mortgage-lenders-that-dont-charge-origination-fees/
//www.cnbc.com/select/best-mortgage-lenders-average-credit-score/
//www.cnbc.com/select/adjustable-rate-mortgage-pros-and-cons/
//www.cnbc.com/select/mortgage-affordability/
#
//www.cnbc.com/select/insurance/
//www.cnbc.com/select/best-life-insurance-companies/
//www.cnbc.com/select/best-homeowners-insurance-companies/
//www.cnbc.com/select/best-renters-insurance-companies/
//www.cnbc.com/select/best-car-insurance-companies/
//www.cnbc.com/select/travel-insurance-guide/
#
//www.cnbc.com/select/credit-monitoring/
//www.cnbc.com/select/best-credit-monitoring-services/
//www.cnbc.com/select/best-identity-theft-protection-services/
//www.cnbc.com/select/how-experian-boost-works/
//www.cnbc.com/select/how-do-credit-repair-services-work/
#
//www.cnbc.com/select/personal-finance/
//www.cnbc.com/select/best-budgeting-apps/
//www.cnbc.com/select/best-expense-tracker-apps/
//www.cnbc.com/select/best-money-transfer-payment-apps/
//www.cnbc.com/select/best-resale-apps-and-websites/
//www.cnbc.com/select/best-buy-now-pay-later-apps/
//www.cnbc.com/select/best-debt-relief-companies/
#
//www.cnbc.com/select/small-business/
//www.cnbc.com/select/best-small-business-savings-accounts/
//www.cnbc.com/select/best-business-checking-accounts/
//www.cnbc.com/select/best-small-business-credit-cards/
//www.cnbc.com/select/best-small-business-loans/
//www.cnbc.com/select/best-tax-software-for-small-businesses/
#
//www.cnbc.com/select/taxes/
//www.cnbc.com/select/best-tax-software/
//www.cnbc.com/select/best-tax-software-for-small-businesses/
//www.cnbc.com/select/how-to-check-the-status-of-your-2020-tax-refund/
#
//www.cnbc.com/select/low-credit-scores/
//www.cnbc.com/select/best-credit-cards-for-bad-credit/
//www.cnbc.com/select/best-personal-loans-for-bad-credit/
//www.cnbc.com/select/best-debt-consolidation-loans-for-bad-credit/
//www.cnbc.com/select/personal-loan-lenders-to-consider-if-you-dont-have-credit-score/
//www.cnbc.com/select/the-best-credit-cards-for-building-credit/
//www.cnbc.com/select/personal-loans-to-apply-credit-score-580-or-lower/
//www.cnbc.com/select/personal-loan-lenders-credit-score-below-670/
//www.cnbc.com/select/best-mortgage-lenders-bad-credit-score/
//www.cnbc.com/select/best-hardship-loans/
//www.cnbc.com/select/how-experian-boost-works/
#
//www.cnbc.com/select/investing/
//www.cnbc.com/select/best-ira-accounts/
//www.cnbc.com/select/best-roth-ira-accounts/
//www.cnbc.com/select/best-investing-apps/
//www.cnbc.com/select/best-brokerage-free-stock-trading/
//www.cnbc.com/select/best-robo-advisors/
//www.cnbc.com/select/what-are-index-funds/
//www.cnbc.com/select/what-are-mutual-funds/
//www.cnbc.com/select/what-are-etfs-should-you-invest/
//www.cnbc.com/select/what-are-bonds/
/?region=usa
/world/
/live-tv/
/watchlist/
#
#
/
/markets/
/business/
/investing/
/technology/
/politics/
/tv/
/watchlist/
/investingclub/
/pro/
https://www.cnbc.com/2023/05/26/european-markets-live-updates-stocks-news-data-and-earnings.html
https://www.cnbc.com/2023/05/26/european-markets-live-updates-stocks-news-data-and-earnings.html
https://www.cnbc.com/quotes/US10Y
https://www.cnbc.com/2023/05/26/a-us-recession-would-be-good-news-for-markets-strategist-says.html
https://www.cnbc.com/2023/05/26/as-china-and-the-us-redefine-geopolitics-europe-faces-a-win-win-situation.html
https://www.cnbc.com/2023/05/26/totalenergies-agm-french-police-fire-tear-gas-at-climate-protesters.html
https://www.cnbc.com/2023/05/25/german-economy-enters-recession-as-first-quarter-gdp-data-is-revised-lower.html
https://www.cnbc.com/2023/05/27/chinas-industrial-profits-tumble-18percent-in-april-as-demand-sputters.html
https://www.cnbc.com/2023/05/27/chinas-industrial-profits-tumble-18percent-in-april-as-demand-sputters.html
https://www.cnbc.com/2023/05/26/us-chinas-top-commerce-officials-meet-to-discuss-trade-concerns.html
https://www.cnbc.com/2023/05/26/as-china-and-the-us-redefine-geopolitics-europe-faces-a-win-win-situation.html
https://www.cnbc.com/2023/05/26/treasury-says-it-wont-run-out-money-until-at-least-june-5-buying-time-for-debt-ceiling-talks.html
https://www.cnbc.com/2023/05/26/treasury-says-it-wont-run-out-money-until-at-least-june-5-buying-time-for-debt-ceiling-talks.html
https://www.cnbc.com/2023/05/26/a-us-recession-would-be-good-news-for-markets-strategist-says.html
https://www.cnbc.com/2023/05/26/a-us-recession-would-be-good-news-for-markets-strategist-says.html
https://www.cnbc.com/2023/05/27/how-janie-deegan-built-janies-life-changing-baked-goods.html
https://www.cnbc.com/2023/05/27/cheapest-places-us-buy-beach-house-realtor.html
https://www.cnbc.com/2023/05/27/mark-cuban-says-elon-musks-twitter-algorithm-is-unfair.html
https://www.cnbc.com/2023/05/27/how-to-invest-as-the-federal-debt-ceiling-deadline-approaches.html
https://www.cnbc.com/2023/05/27/microsoft-keyboard-users-so-devastated-as-accessories-discontinued.html
https://www.cnbc.com/2023/05/27/steve-adcock-the-stupidest-myths-ive-heard-about-early-retirement.html
/pro/
https://www.cnbc.com/2023/05/27/chip-stocks-amd-and-nvidia-are-among-the-most-overbought-stocks-on-wall-street-amid-ai-craze.html
/pro/
https://www.cnbc.com/2023/05/27/analysts-are-pounding-the-table-for-stocks-like-amazon.html
https://www.cnbc.com/2023/05/27/lower-income-americans-pay-for-wealthys-credit-card-rewards-some-economists-say.html
https://www.cnbc.com/2023/05/27/how-mastercard-has-outperformed-visa.html
https://www.cnbc.com/2023/05/27/commercial-real-estate-firms-join-to-recruit-black-student-athletes.html
/pro/
https://www.cnbc.com/2023/05/27/japan-stocks-are-on-fire-this-year-why-this-rally-has-staying-power.html
/pro/
https://www.cnbc.com/2023/05/26/marvell-technology-shares-surge-after-earnings-beat-heres-how-to-play-it.html
https://www.cnbc.com/2023/05/26/tech-stocks-are-back-driven-by-ai-craze-slowing-rate-hikes.html
/pro/
https://www.cnbc.com/2023/05/26/next-week-hints-at-short-lived-debt-deal-relief-as-jobs-report-looms-.html
https://www.cnbc.com/2023/05/26/treasury-says-it-wont-run-out-money-until-at-least-june-5-buying-time-for-debt-ceiling-talks.html
https://www.cnbc.com/2023/05/26/disney-rips-desantis-bid-to-disqualify-judge.html
https://www.cnbc.com/2023/05/26/the-pause-on-student-loan-payments-has-been-a-win-for-public-servants.html
https://www.cnbc.com/2023/05/26/facebook-giphy-sale-shows-how-fear-of-regulators-is-slowing-ma-market.html
https://www.cnbc.com/2023/05/26/job-cuts-jpmorgan-chase-cut-about-500-tech-and-ops-jobs-.html
https://www.cnbc.com/2023/05/26/the-right-age-for-kids-to-be-on-social-media-experts-say.html
/pro/
https://www.cnbc.com/2023/05/26/ai-excitement-leads-to-winning-week-for-nvidia-and-other-tech-stocks.html
/investingclub/
https://www.cnbc.com/2023/05/26/nvidia-shares-jumped-25percent-this-week-and-got-cheaper-heres-why.html
/pro/
https://www.cnbc.com/2023/05/26/needham-this-stock-plays-the-almost-perfect-marriage-between-ai-crypto.html
https://www.cnbc.com/2023/05/26/chatgpt-machine-learning-and-other-popular-ai-terms-to-know.html
https://www.cnbc.com/2023/05/26/taylor-swift-beyonc-metallica-summer-2023s-top-10-hottest-artist-.html
/pro/
https://www.cnbc.com/2023/05/26/investors-shifted-into-these-gold-and-small-cap-etfs-this-week.html
https://www.cnbc.com/2023/05/26/ford-tesla-ev-charging-deal-puts-pressure-on-gm.html
https://www.cnbc.com/2023/05/26/paramount-shares-pop-after-bdt-capital-bets-on-the-media-giants-key-shareholder.html
https://www.cnbc.com/2023/05/26/stocks-making-the-biggest-moves-midday-ford-marvell-technology-paramount-gap-more.html
/us-market-movers/
https://www.cnbc.com/2023/05/27/serbias-president-vucic-steps-down-as-head-of-ruling-party.html
https://www.cnbc.com/2023/05/27/serbias-president-vucic-steps-down-as-head-of-ruling-party.html
https://www.cnbc.com/2023/05/26/tech-stocks-are-back-driven-by-ai-craze-slowing-rate-hikes.html
https://www.cnbc.com/ari-levy/
https://www.cnbc.com/2023/05/26/tech-stocks-are-back-driven-by-ai-craze-slowing-rate-hikes.html
https://www.cnbc.com/ari-levy/
/pro/
https://www.cnbc.com/2023/05/27/japan-stocks-are-on-fire-this-year-why-this-rally-has-staying-power.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/2023/05/27/japan-stocks-are-on-fire-this-year-why-this-rally-has-staying-power.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/2023/05/27/consumers-are-starting-to-fire-up-chinas-economy-etf-experts-find.html
https://www.cnbc.com/sean-conlon/
https://www.cnbc.com/2023/05/27/consumers-are-starting-to-fire-up-chinas-economy-etf-experts-find.html
https://www.cnbc.com/sean-conlon/
https://www.cnbc.com/2023/05/27/vietnam-to-cut-annual-rice-exports-by-44percent-to-4-mln-tonnes-by-2030.html
https://www.cnbc.com/2023/05/27/vietnam-to-cut-annual-rice-exports-by-44percent-to-4-mln-tonnes-by-2030.html
https://www.cnbc.com/2023/05/27/taiwan-reports-chinese-aircraft-carrier-sailed-through-strait.html
https://www.cnbc.com/2023/05/27/taiwan-reports-chinese-aircraft-carrier-sailed-through-strait.html
https://www.cnbc.com/2023/05/26/job-cuts-jpmorgan-chase-cut-about-500-tech-and-ops-jobs-.html
https://www.cnbc.com/hugh-son/
https://www.cnbc.com/2023/05/26/job-cuts-jpmorgan-chase-cut-about-500-tech-and-ops-jobs-.html
https://www.cnbc.com/hugh-son/
https://www.cnbc.com/2023/05/25/worlds-largest-milk-producer-india-faces-15percent-hike-in-milk-prices.html
https://www.cnbc.com/2023/05/25/worlds-largest-milk-producer-india-faces-15percent-hike-in-milk-prices.html
https://www.cnbc.com/2023/05/24/the-no-1-underrated-city-in-the-world-according-to-175-travel-experts-its-poised-to-be-the-hot-new-city.html
https://www.cnbc.com/2023/05/24/the-no-1-underrated-city-in-the-world-according-to-175-travel-experts-its-poised-to-be-the-hot-new-city.html
https://www.cnbc.com/2023/05/26/marvell-shares-soar-25percent-after-semiconductor-firm-beats-on-earnings.html
https://www.cnbc.com/rohan-goswami/
https://www.cnbc.com/2023/05/26/marvell-shares-soar-25percent-after-semiconductor-firm-beats-on-earnings.html
https://www.cnbc.com/rohan-goswami/
https://www.cnbc.com/2023/05/25/stock-market-today-live-updates.html
https://www.cnbc.com/brian-evans/
https://www.cnbc.com/alex-harring/
https://www.cnbc.com/2023/05/25/stock-market-today-live-updates.html
https://www.cnbc.com/brian-evans/
https://www.cnbc.com/alex-harring/
https://www.cnbc.com/2023/05/27/ukraine-targets-russian-oil-pipeline-installations-with-drones-russian-media-reports.html
https://www.cnbc.com/2023/05/27/ukraine-targets-russian-oil-pipeline-installations-with-drones-russian-media-reports.html
https://www.cnbc.com/2023/05/26/inflation-rose-0point4percent-in-april-and-4point7percent-from-a-year-ago-according-to-key-gauge-for-the-fed.html
https://www.cnbc.com/jeff-cox/
https://www.cnbc.com/2023/05/26/inflation-rose-0point4percent-in-april-and-4point7percent-from-a-year-ago-according-to-key-gauge-for-the-fed.html
https://www.cnbc.com/jeff-cox/
/pro/
https://www.cnbc.com/2023/05/26/top-morningstar-strategist-says-these-stocks-are-still-discounted.html
https://www.cnbc.com/weizhen-tan/
https://www.cnbc.com/2023/05/26/top-morningstar-strategist-says-these-stocks-are-still-discounted.html
https://www.cnbc.com/weizhen-tan/
https://www.cnbc.com/2023/05/25/german-economy-enters-recession-as-first-quarter-gdp-data-is-revised-lower.html
https://www.cnbc.com/silvia-amaro/
https://www.cnbc.com/2023/05/25/german-economy-enters-recession-as-first-quarter-gdp-data-is-revised-lower.html
https://www.cnbc.com/silvia-amaro/
https://www.cnbc.com/2023/05/26/openai-ceo-sam-altman-reverses-threat-to-cease-european-operations.html
https://www.cnbc.com/hayden-field/
https://www.cnbc.com/2023/05/26/openai-ceo-sam-altman-reverses-threat-to-cease-european-operations.html
https://www.cnbc.com/hayden-field/
https://www.cnbc.com/2023/05/26/tech-companies-are-laying-off-their-ethics-and-safety-teams-.html
https://www.cnbc.com/hayden-field/
https://www.cnbc.com/jonathan-vanian/
https://www.cnbc.com/2023/05/26/tech-companies-are-laying-off-their-ethics-and-safety-teams-.html
https://www.cnbc.com/hayden-field/
https://www.cnbc.com/jonathan-vanian/
https://www.cnbc.com/2023/05/26/klarna-q1-results-fintech-firm-reports-50percent-reduction-in-net-loss-.html
https://www.cnbc.com/ryan-browne/
https://www.cnbc.com/2023/05/26/klarna-q1-results-fintech-firm-reports-50percent-reduction-in-net-loss-.html
https://www.cnbc.com/ryan-browne/
https://www.cnbc.com/2023/05/26/european-markets-live-updates-stocks-news-data-and-earnings.html
https://www.cnbc.com/jenni-reid/
https://www.cnbc.com/2023/05/26/european-markets-live-updates-stocks-news-data-and-earnings.html
https://www.cnbc.com/jenni-reid/
https://www.cnbc.com/2023/05/26/totalenergies-agm-french-police-fire-tear-gas-at-climate-protesters.html
https://www.cnbc.com/sam-meredith/
https://www.cnbc.com/2023/05/26/totalenergies-agm-french-police-fire-tear-gas-at-climate-protesters.html
https://www.cnbc.com/sam-meredith/
//www.cnbc.com/us-market-movers/
/us-market-movers/
/stocks/
https://www.cnbc.com/2023/05/27/how-mastercard-has-outperformed-visa.html
https://www.cnbc.com/juhohn-lee/
/pro/
https://www.cnbc.com/2023/05/26/next-week-hints-at-short-lived-debt-deal-relief-as-jobs-report-looms-.html
https://www.cnbc.com/scott-schnipper/
/pro/
https://www.cnbc.com/2023/05/26/marvell-technology-shares-surge-after-earnings-beat-heres-how-to-play-it.html
https://www.cnbc.com/christina-falso/
https://www.cnbc.com/2023/05/27/shake-shacks-recent-deal-with-engaged-capital-may-have-fallen-short-for-shareholders.html
https://www.cnbc.com/kenneth-squire/
//www.cnbc.com/live-tv/
//www.cnbc.com/latest-video/
https://www.cnbc.com/video/2023/05/11/why-planes-will-be-powered-by-hydrogen-before-batteries.html
https://www.cnbc.com/video/2023/05/07/how-delta-moves-100000-bags-daily-at-the-worlds-busiest-airport.html
https://www.cnbc.com/video/2023/05/26/jpmorgan-ceo-jamie-dimon-deposed-in-jeffrey-epstein-lawsuits.html
https://www.cnbc.com/special-reports/
https://www.cnbc.com/2023/05/27/steve-adcock-the-stupidest-myths-ive-heard-about-early-retirement.html
https://www.cnbc.com/2023/05/26/gymshark-ceo-ben-francis-from-pizza-hut-sewing-kit-to-billionaire.html
https://www.cnbc.com/2023/05/26/employers-are-learning-gen-z-isnt-the-easiest-generation-to-work-with.html
https://www.cnbc.com/2023/05/24/the-no-1-underrated-city-in-the-world-according-to-175-travel-experts-its-poised-to-be-the-hot-new-city.html
https://www.cnbc.com/2023/05/27/cheapest-places-us-buy-beach-house-realtor.html
https://www.cnbc.com/pro/news/
https://www.cnbc.com/2023/05/27/analysts-are-pounding-the-table-for-stocks-like-amazon.html
/pro/
https://www.cnbc.com/2023/05/27/analysts-are-pounding-the-table-for-stocks-like-amazon.html
https://www.cnbc.com/michael-bloom/
https://www.cnbc.com/2023/05/27/japan-stocks-are-on-fire-this-year-why-this-rally-has-staying-power.html
/pro/
https://www.cnbc.com/2023/05/27/japan-stocks-are-on-fire-this-year-why-this-rally-has-staying-power.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/2023/05/27/chip-stocks-amd-and-nvidia-are-among-the-most-overbought-stocks-on-wall-street-amid-ai-craze.html
/pro/
https://www.cnbc.com/2023/05/27/chip-stocks-amd-and-nvidia-are-among-the-most-overbought-stocks-on-wall-street-amid-ai-craze.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/2023/05/26/next-week-hints-at-short-lived-debt-deal-relief-as-jobs-report-looms-.html
/pro/
https://www.cnbc.com/2023/05/26/next-week-hints-at-short-lived-debt-deal-relief-as-jobs-report-looms-.html
https://www.cnbc.com/scott-schnipper/
https://www.cnbc.com/2023/05/26/marvell-technology-shares-surge-after-earnings-beat-heres-how-to-play-it.html
/pro/
https://www.cnbc.com/2023/05/26/marvell-technology-shares-surge-after-earnings-beat-heres-how-to-play-it.html
https://www.cnbc.com/christina-falso/
https://www.cnbc.com/id/10001247
https://www.cnbc.com/2023/05/26/ukraine-war-live-updates-latest-news-on-russia-and-the-war-in-ukraine.html
https://www.cnbc.com/2023/05/26/ukraine-war-live-updates-latest-news-on-russia-and-the-war-in-ukraine.html
https://www.cnbc.com/amanda-macias/
https://www.cnbc.com/2023/05/25/ukraine-war-live-updates-latest-news-on-russia-and-the-war-in-ukraine.html
https://www.cnbc.com/2023/05/25/ukraine-war-live-updates-latest-news-on-russia-and-the-war-in-ukraine.html
https://www.cnbc.com/amanda-macias/
https://www.cnbc.com/2023/05/25/german-economy-enters-recession-as-first-quarter-gdp-data-is-revised-lower.html

6) Write a python program to scrape the details of most downloaded articles from AI in last 90
days.https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles
Scrape below mentioned details and make data frame

In [13]:
#importing the required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

page=requests.get("https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles")
page

soup=BeautifulSoup(page.text,'html.parser')
soup

Paper_Title=[]
Authors=[]
Pub_Date=[]
Paper_URL=[]


Papers=soup.find_all('h2',class_='sc-1qrq3sd-1 gRGSUS sc-1nmom32-0 sc-1nmom32-1 btcbYu goSKRg')
for i in Papers:
    Paper_Title.append(i.get_text())
    

author=soup.find_all('span',class_='sc-1w3fpd7-0 dnCnAO')
for i in author:
    Authors.append(i.get_text())
    

PubDate=soup.find_all('span',class_='sc-1thf9ly-2 dvggWt')
for i in PubDate:
    Pub_Date.append(i.get_text())


soup2=soup.find('div',class_='sc-orwwe2-3 jOMrrY').find_all('a')
for i in soup2:
    Paper_URL.append(i.get('href', None))

Most_Downloaded=pd.DataFrame({})
Most_Downloaded['Title']=Paper_Title
Most_Downloaded['Author']=Authors
Most_Downloaded['Publish Date']=Pub_Date
Most_Downloaded['URL']=Paper_URL
Most_Downloaded

ConnectionError: HTTPSConnectionPool(host='www.journals.elsevier.com', port=443): Max retries exceeded with url: /artificial-intelligence/most-downloaded-articles (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C2037367C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Write a python program to scrape mentioned details from dineout.co.inand make data framei) Restaurant name
ii) Cuisine
iii) Location
iv) Ratings
v) Image UR

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

page=requests.get("https://www.dineout.co.in/delhi-restaurants/buffet-special")
page

soup=BeautifulSoup(page.text,'html.parser')
soup

Rest_Name=[]
Cuisine=[]
Location=[]
Rating=[]
Image_URL=[]

#to get the restaurant names
Name=soup.find_all('a',class_='restnt-name ellipsis')
for i in Name:
    Rest_Name.append(i.get_text())
    
#to get the cuisine
cui=soup.find_all('span',class_='double-line-ellipsis')
for i in cui:
    Cuisine.append(i.text.split('|')[1])

#to get the Location
Loc=soup.find_all('div',class_='restnt-loc ellipsis')
for i in Loc:
    Location.append(i.get_text())
    
#to get the Rating
Rate=soup.find_all('div',class_='restnt-rating rating-4')
for i in Rate:
    Rating.append(i.get_text())
    
#to get Image_url
imgurl=soup.find_all('img',class_='no-img')
for i in imgurl:
    Image_URL.append(i.get('data-src'))
Rest_Data=pd.DataFrame()
Rest_Data['Title']=Rest_Name
Rest_Data['Cuisine']=Cuisine
Rest_Data['LOcation']=Location
Rest_Data['Rating']=Rating
Rest_Data['ImageURL']=Image_URL
Rest_Data

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(Rest_Data)? (3506913828.py, line 47)